### ISSUE TITLE
report mistakes

### ISSUE THREAD

**Issue by gaufung** [zlotus/notes-linear-algebra#1]
+ **chapter 08** 
The prof. takes  $b_1=1,b_2=5,b_3=6 $ for an example, so 
$
\begin{eqnarray*}
x_1 & + & 2x_3 & = & 1 \\
    &   & 2x_3 & = & 3 \\
\end{eqnarray*}
$
$
\begin{eqnarray*}
x_1 & = & -2 \\
x_3 & = & \frac{3}{2} \\
\end{eqnarray*}
$

+ **chapter 16**
> $Pb$将会把向量投影在$A$的行空间中

Should be 
$Pb$将会把向量投影在$A$的列空间中

**Comment by zlotus** [comment]
Thanks, I've the error in chapter 16. 
But I don't get the equations mentioned in chapter 08, could you make a more specific description? 

Thank you~

**Comment by gaufung** [comment]
> 解法：另所有自由变量取0，则有
X1+2X3 = 0
      2X3 = 0
解得X1 = -2 X3=3/2

The Prof. took _b1=1,b2=5,b3=6_ for example which subjects to _b3-b2-b1 =0_  condition. So if we set free varibales =0 , we should get **X1+2X3 = 1;2X3=3**，and solve this equations.

**Comment by zlotus** [comment]
Sorry, my mistake. 
Thanks a lot~
