### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by henshan2002** [zlotus/notes-linear-algebra#7]
![default](https://cloud.githubusercontent.com/assets/23010531/24077554/d0f924d6-0c8b-11e7-9228-50f6a1d21b16.png)
为什么会铺满整个平面？

**Comment by Theigrams** [comment]
当x,y任意变化时，x(2,-1)+y(-1,2)能到达平面上的任意点，或者说平面上的任意点都能由(2,-1)和(-1,2)的线性组合得到，所以说能铺满整个平面

**Comment by henshan2002** [comment]
明白了，谢谢啦，奔四的大叔向你请教还望不厌其烦！close
